=== rane/gentoo-docs-pl/rane/www/guide.dtd
<!ENTITY doctable SYSTEM "doctable.xml">
<!ENTITY peopletable SYSTEM "peopletable.xml">
<!ENTITY dictionary SYSTEM "dictionary.xml">
<!ENTITY  % style.class	"b|box|brite|c|codenote|comment|e|i|path">
<!ENTITY  % link.class	"uri|mail">
<!ENTITY  % logic.class	"figure|fig|img|br|note|impo|warn|pre|p|table|ul|ol">
<!ENTITY  % all.class	"%logic.class;|%style.class;|%link.class;">

<!ENTITY half   "&#x00BD;"> <!-- VULGAR FRACTION ONE HALF -->
<!ENTITY frac12 "&#x00BD;"> <!-- VULGAR FRACTION ONE HALF -->
<!ENTITY frac14 "&#x00BC;"> <!-- VULGAR FRACTION ONE QUARTER -->
<!ENTITY frac34 "&#x00BE;"> <!-- VULGAR FRACTION THREE QUARTERS -->
<!ENTITY frac18 "&#x215B;"> <!--  -->
<!ENTITY frac38 "&#x215C;"> <!--  -->
<!ENTITY frac58 "&#x215D;"> <!--  -->
<!ENTITY frac78 "&#x215E;"> <!--  -->
<!ENTITY sup1   "&#x00B9;"> <!-- SUPERSCRIPT ONE -->
<!ENTITY sup2   "&#x00B2;"> <!-- SUPERSCRIPT TWO -->
<!ENTITY sup3   "&#x00B3;"> <!-- SUPERSCRIPT THREE -->
<!ENTITY plus   "&#x002B;"> <!-- PLUS SIGN -->
<!ENTITY plusmn "&#x00B1;"> <!-- PLUS-MINUS SIGN -->
<!ENTITY lt     "&#38;#60;"> <!-- LESS-THAN SIGN -->
<!ENTITY equals "&#x003D;"> <!-- EQUALS SIGN -->
<!ENTITY gt     "&#x003E;"> <!-- GREATER-THAN SIGN -->
<!ENTITY divide "&#x00F7;"> <!-- DIVISION SIGN -->
<!ENTITY times  "&#x00D7;"> <!-- MULTIPLICATION SIGN -->
<!ENTITY curren "&#x00A4;"> <!-- CURRENCY SIGN -->
<!ENTITY pound  "&#x00A3;"> <!-- POUND SIGN -->
<!ENTITY dollar "&#x0024;"> <!-- DOLLAR SIGN -->
<!ENTITY cent   "&#x00A2;"> <!-- CENT SIGN -->
<!ENTITY yen    "&#x00A5;"> <!-- YEN SIGN -->
<!ENTITY num    "&#x0023;"> <!-- NUMBER SIGN -->
<!ENTITY percnt "&#x0025;"> <!-- PERCENT SIGN -->
<!ENTITY amp    "&#38;#38;"> <!-- AMPERSAND -->
<!ENTITY ast    "&#x2217;"> <!-- ASTERISK OPERATOR -->
<!ENTITY commat "&#x0040;"> <!-- COMMERCIAL AT -->
<!ENTITY lsqb   "&#x005B;"> <!-- LEFT SQUARE BRACKET -->
<!ENTITY bsol   "&#x005C;"> <!-- REVERSE SOLIDUS -->
<!ENTITY rsqb   "&#x005D;"> <!-- RIGHT SQUARE BRACKET -->
<!ENTITY lcub   "&#x007B;"> <!-- LEFT CURLY BRACKET -->
<!ENTITY horbar "&#x2015;"> <!-- HORIZONTAL BAR -->
<!ENTITY verbar "&#x007C;"> <!-- VERTICAL LINE -->
<!ENTITY rcub   "&#x007D;"> <!-- RIGHT CURLY BRACKET -->
<!ENTITY micro  "&#x00B5;"> <!-- MICRO SIGN -->
<!ENTITY ohm    "&#x2126;"> <!-- OHM SIGN -->
<!ENTITY deg    "&#x00B0;"> <!-- DEGREE SIGN -->
<!ENTITY ordm   "&#x00BA;"> <!-- MASCULINE ORDINAL INDICATOR -->
<!ENTITY ordf   "&#x00AA;"> <!-- FEMININE ORDINAL INDICATOR -->
<!ENTITY sect   "&#x00A7;"> <!-- SECTION SIGN -->
<!ENTITY para   "&#x00B6;"> <!-- PILCROW SIGN -->
<!ENTITY middot "&#x00B7;"> <!-- MIDDLE DOT -->
<!ENTITY larr   "&#x2190;"> <!-- LEFTWARDS DOUBLE ARROW -->
<!ENTITY rarr   "&#x2192;"> <!-- RIGHTWARDS DOUBLE ARROW -->
<!ENTITY uarr   "&#x2191;"> <!-- UPWARDS ARROW -->
<!ENTITY darr   "&#x2193;"> <!-- DOWNWARDS ARROW -->
<!ENTITY copy   "&#x00A9;"> <!-- COPYRIGHT SIGN -->
<!ENTITY reg    "&#x00AE;"> <!-- REG TRADE MARK SIGN -->
<!ENTITY trade  "&#x2122;"> <!-- TRADE MARK SIGN -->
<!ENTITY brvbar "&#x00A6;"> <!-- BROKEN BAR -->
<!ENTITY not    "&#x00AC;"> <!-- NOT SIGN -->
<!ENTITY sung   "&#x2669;"> <!--  -->
<!ENTITY excl   "&#x0021;"> <!-- EXCLAMATION MARK -->
<!ENTITY iexcl  "&#x00A1;"> <!-- INVERTED EXCLAMATION MARK -->
<!ENTITY quot   "&#x0022;"> <!-- QUOTATION MARK -->
<!ENTITY apos   "&#x0027;"> <!-- APOSTROPHE -->
<!ENTITY lpar   "&#x0028;"> <!-- LEFT PARENTHESIS -->
<!ENTITY rpar   "&#x0029;"> <!-- RIGHT PARENTHESIS -->
<!ENTITY comma  "&#x002C;"> <!-- COMMA -->
<!ENTITY lowbar "&#x005F;"> <!-- LOW LINE -->
<!ENTITY hyphen "&#xE4F8;"> <!--  -->
<!ENTITY period "&#x002E;"> <!-- FULL STOP -->
<!ENTITY sol    "&#x002F;"> <!-- SOLIDUS -->
<!ENTITY colon  "&#x003A;"> <!-- COLON -->
<!ENTITY semi   "&#x003B;"> <!-- SEMICOLON -->
<!ENTITY quest  "&#x003F;"> <!-- QUESTION MARK -->
<!ENTITY iquest "&#x00BF;"> <!-- INVERTED QUESTION MARK -->
<!ENTITY laquo  "&#x00AB;"> <!-- LEFT-POINTING DOUBLE ANGLE QUOTATION MARK -->
<!ENTITY raquo  "&#x00BB;"> <!-- RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK -->
<!ENTITY lsquo  "&#x2018;"> <!--  -->
<!ENTITY rsquo  "&#x2019;"> <!-- RIGHT SINGLE QUOTATION MARK -->
<!ENTITY ldquo  "&#x201C;"> <!--  -->
<!ENTITY rdquo  "&#x201D;"> <!-- RIGHT DOUBLE QUOTATION MARK -->
<!ENTITY nbsp   "&#x00A0;"> <!-- NO-BREAK SPACE -->
<!ENTITY shy    "&#x00AD;"> <!-- SOFT HYPHEN -->

<!ELEMENT guide			(title, subtitle?, author+, abstract, license?, version, date, newsitems?, chapter+)>
<!ATTLIST guide			type (project) #IMPLIED
						link CDATA #IMPLIED
						mainpage (yes|no) "no"
						mainid (news|about|contract|packages|graphics|articles|docs|changelog|projects) #IMPLIED>
<!ELEMENT newsitems		(news+)>
<!ELEMENT news			(poster, date, title, body)>
<!ATTLIST news			gentoo (yes|no) "no"
						category (gentoo|main|ibm|linux|moo|nvidia) #REQUIRED>
<!ELEMENT title			(#PCDATA|%style.class;)*>
<!ELEMENT subtitle		(#PCDATA)>
<!ELEMENT author		(#PCDATA|mail)*>
<!ATTLIST author		title CDATA #IMPLIED>
<!ELEMENT abstract		(#PCDATA)>
<!ELEMENT license		EMPTY>
<!ELEMENT version		(#PCDATA)>
<!ELEMENT date			(#PCDATA)>
<!ELEMENT chapter		(title, section+)>
<!ATTLIST chapter   id CDATA #IMPLIED>
<!ELEMENT section		(title?, body)>
<!ATTLIST section   id CDATA #IMPLIED>
<!ELEMENT body			(%all.class;)*>
<!ELEMENT figure		EMPTY>
<!ATTLIST figure		caption CDATA #IMPLIED
						short CDATA #IMPLIED
						link CDATA #REQUIRED>
<!ELEMENT fig			EMPTY>
<!ATTLIST fig			short CDATA #IMPLIED
						linkto CDATA #IMPLIED
						link CDATA #REQUIRED>
<!ELEMENT img			EMPTY>
<!ATTLIST img			src CDATA #REQUIRED>
<!ELEMENT br			(#PCDATA)>
<!ELEMENT note			(#PCDATA|%all.class;)*>
<!ELEMENT impo			(#PCDATA|%all.class;)*>
<!ELEMENT warn			(#PCDATA|%all.class;)*>
<!ELEMENT pre			(#PCDATA|%all.class;)*>
<!ATTLIST pre			caption CDATA #IMPLIED>
<!ELEMENT p				(#PCDATA|%all.class;)*>
<!ELEMENT table			(tcolumn*, tr+)>
<!ELEMENT tcolumn		EMPTY>
<!ATTLIST tcolumn		width CDATA #REQUIRED>
<!ELEMENT tr			(th+|ti+)>
<!ELEMENT th			(#PCDATA|%all.class;)*>
<!ELEMENT ti			(#PCDATA|%all.class;)*>
<!ELEMENT ul			(li+)>
<!ELEMENT ol			(li+)>
<!ELEMENT li			(#PCDATA|%all.class;)*>

<!--STYLE TAGS-->
<!ELEMENT b				(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT brite			(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT box			(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT c				(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT codenote		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT comment		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT e				(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT i				(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT path			(#PCDATA|%style.class;|%link.class;)*>

<!--LINK TAGS-->
<!ELEMENT mail			(#PCDATA|%style.class;)*>
<!ATTLIST mail			link CDATA #REQUIRED>
<!ELEMENT uri			(#PCDATA|%style.class;)*>
<!ATTLIST uri			link CDATA #IMPLIED>

=== rane/gentoo-docs-pl/cla/gnome-2.18-upgrade.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">
<!-- $Header: -->

<guide link="/proj/en/desktop/gnome/howtos/gnome-2.18-upgrade.xml">

<title>Aktualizacja Gnome do wersji 2.18</title>
<author title="Autor">
  <mail link="dang@gentoo.org">Daniel Gryniewicz</mail>
</author>
<author title="Edytor">
<mail link="leio@gentoo.org">Mart Raudsepp</mail>
</author>
<author title="Edytor">
  <mail link="nightmorph@gentoo.org">Joshua Saddler</mail>
</author>
<author title="Edytor, tłumacz">
  <mail link="cla@gentoo.org">Dawid Węgliński</mail>
</author>

<abstract>
Opis procesu aktualizacji GNOME 2.16.x do wersji 2.18.x.
</abstract>

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/2.5 -->
<license/>

<version>1.5</version>
<date>2007-08-18</date>

<chapter>
<title>Główne zmiany</title>
<section>
<title>System dźwięku i ESD</title>
<body>

<p>
Deweloperzy Gnome zdecydowali usunąć możliwości esd, ponieważ były zepsute i
prowadziły do wielu problemów. Znaczy to, że używając tego systemu dźwięku
należy mieć go uruchamianego podczas ładowania systemu. Robi się to tak:
</p>

<pre caption="Aktywacja esound podczas ładowania systemu">
# <i>rc-update add esound default</i>
</pre>

<p>
Trzeba mieć na uwdze, że esound nie zostanie uruchomiony aż do następnego
restartu systemu. Aby usługa ta została uruchomiona natychmiast, trzeba wykonać
następujące polecenie:
</p>

<pre caption="Aktywacja esound">
# <i>/etc/init.d/esound start</i>
</pre>

</body>
</section>
<section>
<title>Totem nie ma flagi xine!</title>
<body>

<p>
Zespół Gnome zdecydował usunąć flagę xine z powodu błędów, których nie da się
naprawić w prosty sposób. Jasne jest, że sprawia to problemy podczas odtwarzania
płyt DVD, jednak jest to dalej możliwe. Należy mieć pewność, że totem był
zbudowany z flagą dvd, a następnie uruchomić go:
</p>

<pre caption="Odtwarzanie DVD w totemie">
# <i>totem dvd://</i>
</pre>

<p>
Pozwoli to jedynie odtworzyć płytę, niestety bez menu.
</p>

<p>
Ciągle trwają prace nad stworzeniem możliwości użycia xine w totemie wraz z
gstreamerem. Wciąż jednak będzie to niewspierane i wciąż będzie więcej problemów
niż korzyści. Wszelka pomoc w naprawieniu tego problemu zostanie doceniona.
</p>

</body>
</section>
<section>
<title>Flagi przeglądarki pluginów w totemie się zmieniły! Teraz dostaję
seamonkey!</title>
<body>

<p>
Flagi USE dla gecko zostały zmienione. Dawniej domyślną była seamonkey z
możliwością wyboru firefox lub xulrunner. Obecnie domyślną jest firefox i
możliwość wyboru xulrunner lub seamonkey. Jest tak z dwóch powodów. Po pierwsze,
seamonkey seamonkey nie uruchamia się na wszystkich architekturach, więc
potrzeba flagi USE, którą można zamaskować w profilu. Po drugie, aby totem mógł
współpracować z innymi Gnomowymi aplikacjami, takimi jak epiphany. Poniżej jest
lista możliwych kombinacji flag oraz opis ich działania:
</p>

<table>
<tr>
  <th colspan="2">Różne warianty zastosowania flag USE w totemie</th>
</tr>
<tr>
  <th>Flaga USE</th>
  <th>Rezultat</th>
</tr>
<tr>
  <ti>USE="<c>-nsplugin</c>"</ti>
  <ti>Dezaktywacja przeglądarki pluginów i odrzucenie gecko z zależności</ti>
</tr>
<tr>
  <ti>USE="<c>nsplugin -xulrunner -seamonkey</c>"</ti>
  <ti>
    Buduje plugin na podstawie firefoxa. Jest to domyślna opcja we wszystkich
    proilach.
  </ti>
</tr>
<tr>
  <ti>USE="<c>nsplugin xulrunner -seamonkey</c>"</ti>
  <ti>Buduje plugin na podstawie xulrinner.</ti>
</tr>
<tr>
  <ti>USE="<c>nsplugin xulrunner seamonkey</c>"</ti>
  <ti>Buduje plugin na podstawie xulrunner. (xulrunner gryzie seamonkey).</ti>
</tr>
<tr>
  <ti>USE="<c>nsplugin -xulrunner seamonkey</c>"</ti>
  <ti>Buduje plugin na podstawie seamonkey.</ti>
</tr>
</table>

</body>
</section>
</chapter>

<chapter>
<title>Znane problemy</title>
<section>
<title>Brakujące ikony w tacce systemowej (szczególnie
gnome-power-manager)</title>
<body>

<p>
W 2.18 na tacce systemowej może brakować niektórych ikon. Powinny one się
pojawić dla aplikacji uruchomianych wraz z sesją Gnome. Program jest
uruchomiony, lecz brakuje jego ikony w tacce. Najczęściej przytrafia się to 
menadżerowi energii (gnome-power-manager). Mamy nadzieję, że błąd ten zostanie
naprawiony w przyszłości. Niestety w chwili obecnej obejściem tego problemu musi
być ponowne uruchomienie programu zaraz po starcie sesji Gnome. W tym celu
należy uruchomić terminal i wykonać poniższe polecenia:
</p>

<pre caption="Przywrócenie ikony gnome-power-manager w tacce systemowej">
# <i>killall gnome-power-manager</i>
# <i>gnome-power-manager</i>
</pre>

<p>
Przywróci to ikonę g-p-m w tacce systemowej aż do końca sesji.
</p>

</body>
</section>
<section>
<title>Błędy podczas logowania w Deskbar-applet</title>
<body>

<p>
W demonie trackerd jest błąd, który powoduje "sytuację wyścigu", w którym
trackerd jest uruchamiany, a deskbar jednocześnie próbuje go uruchomić poprzez
interfejs dbus. Powoduje to błąd w działaniu deskbar-applet.
</p>

<pre caption="Naprawa deskbar-applet">
# <i>killall deskbar-applet</i>
</pre>

<p>
Kiedy pojawi się okienko dialogowe z pytaniem o ponowne uruchomienie, należy
wybrać "Przeładuj".
</p>

<p>
Wystarczy, że wykona się to jeden raz po zalogowaniu. Deskbar-applet będzie
wtedy działał do końca sesji.
</p>

</body>
</section>
<section>
<title>Kompilacja kończy się niepowodzeniem z błędem XML::</title>
<body>

<p>
Zdarza się tak ponieważ <c>expat</c> został przeniesiony do stabilnej gałęźi
drzewa w tym samym czasie co Gnome 2.18. Należy przebudować wszystko, co jest
zlinkowane. Aby to zrobić, należy wykonać polecenie:
</p>

<pre caption="Naprawa błędów expat">
# <i>revdep-rebuild -X</i>
</pre>

<p>
Zostanie naprawione wszystko, co jest zepsute przez expat. Kiedy już się to
skończy, należy kontunuować aktualizację Gnome.
</p>

<p>
Kiedy aktualizacja Gnome 2.18 zostanie zakończona pomyślnie, należy jeszcze raz
uruchomić <c>revdep-rebuild</c> aby wszystkie zależności zostały prawidłowo
zbudowane. Należy pamiętać, aby na koniec uruchomić <c>dispatch-conf</c>!
</p>

<p>
Jeśli podczas procesu aktualizacji dbus i hal były uruchomione, należy je
zrestartować:
</p>

<pre caption="Ponowne uruchomienie usług">
# <i>/etc/init.d/dbus restart</i>
# <i>/etc/init.d/hald restart</i>
</pre>

</body>
</section>
</chapter>
</guide>

=== rane/gentoo-docs-pl/rane/tlumaczenie-manuali.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">

<guide link="tlumaczenie-manuali.html" lang="pl">
<title>Polski projekt tłumaczenia manuali Gentoo</title>

<author title="Autor">
  <mail link="damjanek@gentoo.pl">Damian Szeluga</mail>
</author>

<abstract>
Oficjalna strona polskiego projektu tłumaczenia manuali Gentoo.
</abstract>

<version>1.1.4</version>
<date>2006-05-26</date>

<chapter>
<title>Zasady tłumaczenia</title>
<section>
<body>

<p>
Sprawa jest dość prosta, tłumaczymy wszystkie manuale związane bezpośrednio z
Portage. Zaczynamy od wersji niestabilnej Portage, czyli w tym wypadku od
<c>portage-2.1_pre4</c>. Tłumaczymy także manuale związane z pakietem
gentoolkit, są one takie same zarówno w wersji stabilnej jak i niestabilnej.
</p>

<p>
Priorytetem jest wierność tłumaczenia oryginałowi, każda merytoryczna pomyłka
może tu oznaczać poważne komplikacje dla użytkownika.
</p>

<p>
Lista manuali instalowanych przez Portage:
</p>

<table>
<tr>
<th>Strona man</th>
<th>Tłumacz</th>
<th>Angielski man</th>
<th>Polski man</th>
<th>Wersja HTML</th>
</tr><tr>
<ti>dispatch-conf.1</ti>
<ti>rane</ti>
<ti><uri link="man-pages/portage/2.1_rc4/en/dispatch-conf.1.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/dispatch-conf.1.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/html/dispatch-conf.1.txt.html">2.1_rc4</uri></ti>
</tr><tr>
<ti>ebuild.1</ti>
<ti>stawrul</ti>
<ti><uri link="man-pages/portage/2.1_rc4/en/ebuild.1.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/ebuild.1.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/html/ebuild.1.txt.html">2.1_rc4</uri></ti>
</tr><tr>
<ti>ebuild.5</ti>
<ti>iieee</ti>
<ti><uri link="man-pages/portage/2.1_rc4/en/ebuild.5.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/ebuild.5.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/html/ebuild.5.txt.html">2.1_rc4</uri></ti>
</tr><tr>
<ti>emaint.1</ti>
<ti>rane</ti>
<ti><uri link="man-pages/portage/2.1_rc4/en/emaint.1.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/emaint.1.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/html/emaint.1.txt.html">2.1_rc4</uri></ti>
</tr><tr>
<ti>emerge.1</ti>
<ti>Damjanek</ti>
<ti><uri link="man-pages/portage/2.1_rc4/en/emerge.1.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/emerge.1.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/html/emerge.1.txt.html">2.1_rc4</uri></ti>
</tr><tr>
<ti>env-update.1</ti>
<ti>rane</ti>
<ti><uri link="man-pages/portage/2.1_rc4/en/env-update.1.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/env-update.1.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/html/env-update.1.txt.html">2.1_rc4</uri></ti>
</tr><tr>
<ti>etc-update.1</ti>
<ti>rane</ti>
<ti><uri link="man-pages/portage/2.1_rc4/en/etc-update.1.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/etc-update.1.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/html/etc-update.1.txt.html">2.1_rc4</uri></ti>
</tr><tr>
<ti>make.conf.5</ti>
<ti>ShadoWW</ti>
<ti><uri link="man-pages/portage/2.1_rc4/en/make.conf.5.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/make.conf.5.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/html/make.conf.5.txt.html">2.1_rc4</uri></ti>
</tr><tr>
<ti>portage.5</ti>
<ti>moloh</ti>
<ti><uri link="man-pages/portage/2.1_rc4/en/portage.5.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/portage.5.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/html/portage.5.txt.html">2.1_rc4</uri></ti>
</tr><tr>
<ti>quickpkg.1</ti>
<ti>rane</ti>
<ti><uri link="man-pages/portage/2.1_rc4/en/quickpkg.1.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/quickpkg.1.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/html/quickpkg.1.txt.html">2.1_rc4</uri></ti>
</tr><tr>
<ti>repoman.1</ti>
<ti>Shadoww</ti>
<ti><uri link="man-pages/portage/2.1_rc4/en/repoman.1.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/repoman.1.txt">2.1_rc4</uri></ti>
<ti><uri link="man-pages/portage/2.1_rc4/pl/html/repoman.1.txt.html">2.1_rc4</uri></ti>
</tr>
</table>

<p>
Lista manuali instalowanych przez gentoolkit:
</p>

<table>
<tr>
<th>Strona man</th>
<th>Tłumacz</th>
<th>Angielski man</th>
<th>Polski man</th>
<th>Wersja HTML</th>
</tr><tr>
<ti>eclean.1</ti>
<ti>heavy_metal</ti>
<ti><uri link="man-pages/gentoolkit/0.2.2_pre2/en/eclean.1.txt">0.2.2_pre2</uri></ti>
<ti>-</ti>
<ti>-</ti>
</tr><tr>
</tr><tr>
<ti>equery.1</ti>
<ti>ShadoWW</ti>
<ti><uri link="man-pages/gentoolkit/0.2.2_pre2/en/equery.1.txt">0.2.2_pre2</uri></ti>
<ti>-</ti>
<ti>-</ti>
</tr><tr>
<ti>etcat.1</ti>
<ti>heavy_metal</ti>
<ti><uri link="man-pages/gentoolkit/0.2.2_pre2/en/etcat.1.txt">0.2.2_pre2</uri></ti>
<ti>-</ti>
<ti>-</ti>
</tr><tr>
<ti>euse.1</ti>
<ti>keybi</ti>
<ti><uri link="man-pages/gentoolkit/0.2.2_pre2/en/euse.1.txt">0.2.2_pre2</uri></ti>
<ti><uri link="man-pages/gentoolkit/0.2.2_pre2/pl/euse.1.txt">0.2.2_pre2</uri></ti>
<ti><uri link="man-pages/gentoolkit/0.2.2_pre2/pl/html/euse.1.html">0.2.2_pre2</uri></ti>

</tr><tr>
<ti>glsa-check.1</ti>
<ti>gogiel</ti>
<ti><uri link="man-pages/gentoolkit/0.2.2_pre2/en/glsa-check.1.txt">0.2.2_pre2</uri></ti>
<ti><uri link="man-pages/gentoolkit/0.2.2_pre2/pl/glsa-check.1.txt">0.2.2_pre2</uri></ti>
<ti><uri link="man-pages/gentoolkit/0.2.2_pre2/pl/html/glsa-check.1.html">0.2.2_pre2</uri></ti>
</tr><tr>
<ti>qpkg.1</ti>
<ti>chojny</ti>
<ti><uri link="man-pages/gentoolkit/0.2.2_pre2/en/qpkg.1.txt">0.2.2_pre2</uri></ti>
<ti>-</ti>
<ti>-</ti>
</tr><tr>
<ti>revdep-rebuild.1</ti>
<ti>yan</ti>
<ti><uri link="man-pages/gentoolkit/0.2.2_pre2/en/revdep-rebuild.1.txt">0.2.2_pre2</uri></ti>
<ti><uri link="man-pages/gentoolkit//0.2.2_pre2/pl/revdep-rebuild.1.txt">0.2.2_pre2</uri></ti>
<ti><uri link="man-pages/gentoolkit//0.2.2_pre2/pl/html/revdep-rebuild.1.html">0.2.2_pre2</uri></ti>
</tr>
</table>

<p>
Pozostałe strony man:
</p>

<table>
<tr>
<th>Strona man</th>
<th>Tłumacz</th>
<th>Angielski man</th>
<th>Polski man</th>
<th>Wersja HTML</th>
</tr><tr>
<ti>genlop</ti>
<ti>steiner</ti>
<ti><uri link="man-pages/other/genlop/0.30.5/en/genlop.1.txt">0.30.5</uri></ti>
<ti><uri link="man-pages/other/genlop/0.30.5/pl/genlop.1.txt">0.30.5</uri></ti>
<ti><uri link="man-pages/other/genlop/0.30.5/pl/html/genlop.1.html">0.30.5</uri></ti>
</tr><tr>
<ti>eix</ti>
<ti>prizman</ti>
<ti><uri link="man-pages/other/eix/0.5.1-r1/en/eix.1.in.txt">0.5.1-r1</uri></ti>
<ti>-</ti>
<ti>-</ti>
</tr>
</table>


<p>
Jak wygląda cały proces?
</p>

<p>
Kopiujemy plik z manem do katalogu domowego, otwieramy vimem i tłumaczymy tak
jak zwykły XML. Potem dzielimy się nim z koordynatorem i po sprawie.
Przed rozpoczęciem tłumaczenia należy zgłosić, że zamierzamy nim się zajmować,
zostanie to uwzględnione na powyższej liście.
</p>

<p>
Na końcu tłumaczonego pliku należy dodać podpis, jego format jest następujący:
</p>

<pre caption="Format podpisu tłumaczonej strony man">
.SH TŁUMACZENIE
Imię Nazwisko &lt;adres@email.pl&gt;
.br 
Polski projekt tłumaczenia manuali Gentoo
.br 
http://gentoo.org/~rane/tlumaczenie-manuali.html
</pre>

<p>
Jeśli chodzi o aktualizowanie manuali, tu również sprawa nie jest
skomplikowana. Wraz z wydaniem nowej wersji Portage, katalog z manualami będzie
diffowany z wersją poprzednią, a naniesione tam przez deweloperów poprawki
publikowane na tej stronie, a następnie nanoszone na odpowiednie dokumenty.
</p>

<p>
W razie pytań co do terminologii, wszelkich problemów technicznych, sugestii i
jakichkolwiek wątpliwości, należy pisać na adres <mail>damjanek@gentoo.pl</mail>
lub wejść na kanał <c>#gentoo-docs-pl</c> w sieci FreeNode.
</p>

</body>
</section>
</chapter>
</guide>
