=== rane/gentoo-docs-pl/rane/www/guide.dtd
<!ENTITY doctable SYSTEM "doctable.xml">
<!ENTITY peopletable SYSTEM "peopletable.xml">
<!ENTITY dictionary SYSTEM "dictionary.xml">
<!ENTITY  % style.class	"b|box|brite|c|codenote|comment|e|i|path">
<!ENTITY  % link.class	"uri|mail">
<!ENTITY  % logic.class	"figure|fig|img|br|note|impo|warn|pre|p|table|ul|ol">
<!ENTITY  % all.class	"%logic.class;|%style.class;|%link.class;">

<!ENTITY half   "&#x00BD;"> <!-- VULGAR FRACTION ONE HALF -->
<!ENTITY frac12 "&#x00BD;"> <!-- VULGAR FRACTION ONE HALF -->
<!ENTITY frac14 "&#x00BC;"> <!-- VULGAR FRACTION ONE QUARTER -->
<!ENTITY frac34 "&#x00BE;"> <!-- VULGAR FRACTION THREE QUARTERS -->
<!ENTITY frac18 "&#x215B;"> <!--  -->
<!ENTITY frac38 "&#x215C;"> <!--  -->
<!ENTITY frac58 "&#x215D;"> <!--  -->
<!ENTITY frac78 "&#x215E;"> <!--  -->
<!ENTITY sup1   "&#x00B9;"> <!-- SUPERSCRIPT ONE -->
<!ENTITY sup2   "&#x00B2;"> <!-- SUPERSCRIPT TWO -->
<!ENTITY sup3   "&#x00B3;"> <!-- SUPERSCRIPT THREE -->
<!ENTITY plus   "&#x002B;"> <!-- PLUS SIGN -->
<!ENTITY plusmn "&#x00B1;"> <!-- PLUS-MINUS SIGN -->
<!ENTITY lt     "&#38;#60;"> <!-- LESS-THAN SIGN -->
<!ENTITY equals "&#x003D;"> <!-- EQUALS SIGN -->
<!ENTITY gt     "&#x003E;"> <!-- GREATER-THAN SIGN -->
<!ENTITY divide "&#x00F7;"> <!-- DIVISION SIGN -->
<!ENTITY times  "&#x00D7;"> <!-- MULTIPLICATION SIGN -->
<!ENTITY curren "&#x00A4;"> <!-- CURRENCY SIGN -->
<!ENTITY pound  "&#x00A3;"> <!-- POUND SIGN -->
<!ENTITY dollar "&#x0024;"> <!-- DOLLAR SIGN -->
<!ENTITY cent   "&#x00A2;"> <!-- CENT SIGN -->
<!ENTITY yen    "&#x00A5;"> <!-- YEN SIGN -->
<!ENTITY num    "&#x0023;"> <!-- NUMBER SIGN -->
<!ENTITY percnt "&#x0025;"> <!-- PERCENT SIGN -->
<!ENTITY amp    "&#38;#38;"> <!-- AMPERSAND -->
<!ENTITY ast    "&#x2217;"> <!-- ASTERISK OPERATOR -->
<!ENTITY commat "&#x0040;"> <!-- COMMERCIAL AT -->
<!ENTITY lsqb   "&#x005B;"> <!-- LEFT SQUARE BRACKET -->
<!ENTITY bsol   "&#x005C;"> <!-- REVERSE SOLIDUS -->
<!ENTITY rsqb   "&#x005D;"> <!-- RIGHT SQUARE BRACKET -->
<!ENTITY lcub   "&#x007B;"> <!-- LEFT CURLY BRACKET -->
<!ENTITY horbar "&#x2015;"> <!-- HORIZONTAL BAR -->
<!ENTITY verbar "&#x007C;"> <!-- VERTICAL LINE -->
<!ENTITY rcub   "&#x007D;"> <!-- RIGHT CURLY BRACKET -->
<!ENTITY micro  "&#x00B5;"> <!-- MICRO SIGN -->
<!ENTITY ohm    "&#x2126;"> <!-- OHM SIGN -->
<!ENTITY deg    "&#x00B0;"> <!-- DEGREE SIGN -->
<!ENTITY ordm   "&#x00BA;"> <!-- MASCULINE ORDINAL INDICATOR -->
<!ENTITY ordf   "&#x00AA;"> <!-- FEMININE ORDINAL INDICATOR -->
<!ENTITY sect   "&#x00A7;"> <!-- SECTION SIGN -->
<!ENTITY para   "&#x00B6;"> <!-- PILCROW SIGN -->
<!ENTITY middot "&#x00B7;"> <!-- MIDDLE DOT -->
<!ENTITY larr   "&#x2190;"> <!-- LEFTWARDS DOUBLE ARROW -->
<!ENTITY rarr   "&#x2192;"> <!-- RIGHTWARDS DOUBLE ARROW -->
<!ENTITY uarr   "&#x2191;"> <!-- UPWARDS ARROW -->
<!ENTITY darr   "&#x2193;"> <!-- DOWNWARDS ARROW -->
<!ENTITY copy   "&#x00A9;"> <!-- COPYRIGHT SIGN -->
<!ENTITY reg    "&#x00AE;"> <!-- REG TRADE MARK SIGN -->
<!ENTITY trade  "&#x2122;"> <!-- TRADE MARK SIGN -->
<!ENTITY brvbar "&#x00A6;"> <!-- BROKEN BAR -->
<!ENTITY not    "&#x00AC;"> <!-- NOT SIGN -->
<!ENTITY sung   "&#x2669;"> <!--  -->
<!ENTITY excl   "&#x0021;"> <!-- EXCLAMATION MARK -->
<!ENTITY iexcl  "&#x00A1;"> <!-- INVERTED EXCLAMATION MARK -->
<!ENTITY quot   "&#x0022;"> <!-- QUOTATION MARK -->
<!ENTITY apos   "&#x0027;"> <!-- APOSTROPHE -->
<!ENTITY lpar   "&#x0028;"> <!-- LEFT PARENTHESIS -->
<!ENTITY rpar   "&#x0029;"> <!-- RIGHT PARENTHESIS -->
<!ENTITY comma  "&#x002C;"> <!-- COMMA -->
<!ENTITY lowbar "&#x005F;"> <!-- LOW LINE -->
<!ENTITY hyphen "&#xE4F8;"> <!--  -->
<!ENTITY period "&#x002E;"> <!-- FULL STOP -->
<!ENTITY sol    "&#x002F;"> <!-- SOLIDUS -->
<!ENTITY colon  "&#x003A;"> <!-- COLON -->
<!ENTITY semi   "&#x003B;"> <!-- SEMICOLON -->
<!ENTITY quest  "&#x003F;"> <!-- QUESTION MARK -->
<!ENTITY iquest "&#x00BF;"> <!-- INVERTED QUESTION MARK -->
<!ENTITY laquo  "&#x00AB;"> <!-- LEFT-POINTING DOUBLE ANGLE QUOTATION MARK -->
<!ENTITY raquo  "&#x00BB;"> <!-- RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK -->
<!ENTITY lsquo  "&#x2018;"> <!--  -->
<!ENTITY rsquo  "&#x2019;"> <!-- RIGHT SINGLE QUOTATION MARK -->
<!ENTITY ldquo  "&#x201C;"> <!--  -->
<!ENTITY rdquo  "&#x201D;"> <!-- RIGHT DOUBLE QUOTATION MARK -->
<!ENTITY nbsp   "&#x00A0;"> <!-- NO-BREAK SPACE -->
<!ENTITY shy    "&#x00AD;"> <!-- SOFT HYPHEN -->

<!ELEMENT guide			(title, subtitle?, author+, abstract, license?, version, date, newsitems?, chapter+)>
<!ATTLIST guide			type (project) #IMPLIED
						link CDATA #IMPLIED
						mainpage (yes|no) "no"
						mainid (news|about|contract|packages|graphics|articles|docs|changelog|projects) #IMPLIED>
<!ELEMENT newsitems		(news+)>
<!ELEMENT news			(poster, date, title, body)>
<!ATTLIST news			gentoo (yes|no) "no"
						category (gentoo|main|ibm|linux|moo|nvidia) #REQUIRED>
<!ELEMENT title			(#PCDATA|%style.class;)*>
<!ELEMENT subtitle		(#PCDATA)>
<!ELEMENT author		(#PCDATA|mail)*>
<!ATTLIST author		title CDATA #IMPLIED>
<!ELEMENT abstract		(#PCDATA)>
<!ELEMENT license		EMPTY>
<!ELEMENT version		(#PCDATA)>
<!ELEMENT date			(#PCDATA)>
<!ELEMENT chapter		(title, section+)>
<!ATTLIST chapter   id CDATA #IMPLIED>
<!ELEMENT section		(title?, body)>
<!ATTLIST section   id CDATA #IMPLIED>
<!ELEMENT body			(%all.class;)*>
<!ELEMENT figure		EMPTY>
<!ATTLIST figure		caption CDATA #IMPLIED
						short CDATA #IMPLIED
						link CDATA #REQUIRED>
<!ELEMENT fig			EMPTY>
<!ATTLIST fig			short CDATA #IMPLIED
						linkto CDATA #IMPLIED
						link CDATA #REQUIRED>
<!ELEMENT img			EMPTY>
<!ATTLIST img			src CDATA #REQUIRED>
<!ELEMENT br			(#PCDATA)>
<!ELEMENT note			(#PCDATA|%all.class;)*>
<!ELEMENT impo			(#PCDATA|%all.class;)*>
<!ELEMENT warn			(#PCDATA|%all.class;)*>
<!ELEMENT pre			(#PCDATA|%all.class;)*>
<!ATTLIST pre			caption CDATA #IMPLIED>
<!ELEMENT p				(#PCDATA|%all.class;)*>
<!ELEMENT table			(tcolumn*, tr+)>
<!ELEMENT tcolumn		EMPTY>
<!ATTLIST tcolumn		width CDATA #REQUIRED>
<!ELEMENT tr			(th+|ti+)>
<!ELEMENT th			(#PCDATA|%all.class;)*>
<!ELEMENT ti			(#PCDATA|%all.class;)*>
<!ELEMENT ul			(li+)>
<!ELEMENT ol			(li+)>
<!ELEMENT li			(#PCDATA|%all.class;)*>

<!--STYLE TAGS-->
<!ELEMENT b				(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT brite			(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT box			(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT c				(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT codenote		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT comment		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT e				(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT i				(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT path			(#PCDATA|%style.class;|%link.class;)*>

<!--LINK TAGS-->
<!ELEMENT mail			(#PCDATA|%style.class;)*>
<!ATTLIST mail			link CDATA #REQUIRED>
<!ELEMENT uri			(#PCDATA|%style.class;)*>
<!ATTLIST uri			link CDATA #IMPLIED>

=== rane/gentoo-docs-pl/rane/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">

<guide link="jak-tlumaczyc.xml" lang="pl">
<title>Polski projekt tłumaczenia dokumentacji Gentoo</title>

<author title="Autor">
  <mail link="rane@gentoo.org">Łukasz Damentko</mail>
</author>

<abstract>
Oficjalna strona polskiego projektu tłumaczenia dokumentacji Gentoo.
</abstract>

<version>1.0</version>
<date>2006-02-07</date>

<chapter>
<title>Wprowadzenie</title>
<section>
<body>

<p>
Głównym celem polskiego projektu tłumaczenia dokumentacji Gentoo jest
przetłumaczenie jak największej części dokumentacji Gentoo Linux. Umożliwi to
korzystanie z naszej dystrybucji także użytkownikom nie znającym języka
angielskiego lub znającym go słabo. Na tej stronie przedstawiamy status
tłumaczeń oraz wszelkie niezbędne informacje dla ludzi chętnych do współpracy.
</p>

<p>
Wszystkie dokumenty, które są przez nas tłumaczone są częścią oficjalnej
dokumentacji Gentoo, a ich lista znajduje się pod adresem
<uri>http://gentoo.org/doc/pl/list.xml</uri>. Początkujących użytkowników
szczególnie zachęcamy do zapoznania się z <uri
link="http://gentoo.org/doc/pl/handbook/">Podręcznikiem Gentoo</uri> opisującym
proces instalacji oraz podstawy pracy z Gentoo.
</p>

<p>
Dokumentacja Gentoo jest wydawana na zasadach licencji <uri
link="http://creativecommons.org/licenses/by-sa/2.5/">Creative Commons - Share
Alike</uri>. Dotyczy to również wszystkich jej tłumaczeń, o ile w konkretnym
dokumencie nie znajduje się inna informacja.
</p>

</body>
</section>
</chapter>

<chapter>
<title>Informacje dla tłumaczy</title>
<section>
<body>

<p>
Wszystkie informacje z jakimi powinni zapoznać się tłumacze spisaliśmy w osobnym
<uri link="http://dev.gentoo.org/~rane/jak-tlumaczyc.xml">dokumencie</uri>. Jest
on obowiązkową lekturą dla każdego, kto zamierza dołączyć do naszego projektu.
Osoby zainteresowane pomocą w aktualizowaniu dokumentacji powinny zapoznać się z
<uri link="http://dev.gentoo.org/~rane/jak-aktualizowac.xml">opisem</uri>
wszystkich czynności jakich trzeba w tym celu dokonać.
</p>

<p>
Po zapoznaniu się z powyższym tekstem wystarczy wysłać zgłoszenie pod adres
<mail>rane@gentoo.org</mail>. Na adres ten można również wysyłać wszelkie
pytania i sugestie dotyczące projektu oraz już przetłumaczonej dokumentacji.
Jest to służbowa skrzynka koordynatora projektu.
</p>

<p>
Postęp prac nad dokumentacją można śledzić w oficjalnym <uri
link="http://sources.gentoo.org/viewcvs.py/gentoo/xml/htdocs/doc/pl/">repozytorium
CVS</uri> projektu Gentoo.
</p>

<p>
Dzięki uprzejmości osób administrujących projektem <uri
link="http://www.gentoo.org/proj/en/overlays/">Gentoo Overlays</uri> projekt
dysponuje także nieoficjalnym (roboczym) <uri
link="http://overlays.gentoo.org/proj/docs-pl/browser">repozytorium SVN</uri>.
Dostęp do niego można uzyskać kontaktując się z <mail
link="rane@gentoo.org">koordynatorem</mail> projektu. Mogą z niego korzystać
wszystkie osoby pomagające w pracy nad polską dokumentacją Gentoo.
</p>

<p>
Z uczestnikami projektu można porozmawiać na naszym oficjalnym kanale
<c>#gentoo-docs-pl</c> w sieci <uri link="http://freenode.net/">freenode</uri>.
Zapraszamy również tam.
</p>

</body>
</section>
</chapter>

<chapter>
<title>Strony</title>
<section>
<body>

<ul>
  <li>
    <uri link="http://dev.gentoo.org/~shadoww/trads.xml">Tabela</uri> przedstawiająca listę wszystkich
    przetłumaczonych dokumentów
  </li>
  <li>
    <uri link="http://dev.gentoo.org/~shadoww/trads-0.xml">Skrócona wersja</uri> powyższej tabeli, przedstawiająca
    jedynie dokumenty wymagające aktualizacji
  </li>
</ul>

<ul>
  <li><uri link="jak-tlumaczyc.xml">Instrukcje dla tłumaczy</uri></li>
  <li><uri link="jak-aktualizowac.xml">Opis aktualizowania dokumentów</uri></li>
  <li><uri link="tlumaczenie-manuali.xml">Projekt tłumaczenia manuali Gentoo</uri></li>
  <li><uri link="http://sources.gentoo.org/viewcvs.py/gentoo/xml/htdocs/doc/pl/">Katalog z polską dokumentacją w CVS Gentoo</uri></li>
  <li><uri link="http://overlays.gentoo.org/proj/docs-pl/browser">Robocze repozytorium SVN projektu</uri></li>
  <li><uri link="http://gentoo.org/news/pl/gwn/gwn.xml">Bratni projekt tłumaczenia Tygodnika Gentoo</uri></li>
</ul>

<ul>
  <li>
    <uri link="http://dev.gentoo.org/~rane/docget.py">Program docget</uri>
  </li>
  <li>  
    <uri link="http://dev.gentoo.org/~rane/tlumacz">Skrypt tlumacz</uri>
  </li>
  <li>
    <uri link="http://dev.gentoo.org/~rane/slownik.gz">Słownik</uri>
  </li>
</ul>

<ul>
  <li>
    <uri link="http://gentoo.org/proj/en/gdp/tests/topdocs.xml">Statystyki</uri>
    poczytności poszczególnych dokumentów na stronach Gentoo
  </li>
  <li>
    <uri link="http://dev.gentoo.org/~rane/other/status.html">Statystyki</uri>
    dotyczące ilości przetłumaczonych dokumentów
  </li>
</ul>

<pre caption="Pobieranie repozytoriów ze źródłami polskiej dokumentacji">
<comment>(Nieoficjalne robocze repozytorium na overlays.gentoo.org)</comment>
$ <i>svn co http://overlays.gentoo.org/svn/proj/docs-pl/</i>
<comment>(Dokumentacja z gentoo.org)</comment>
$ <i>cvs -d :pserver:anonymous@anoncvs.gentoo.org/var/cvsroot co gentoo/xml/htdocs/doc/pl</i>
</pre>

</body>
</section>
</chapter>

<chapter>
<title>Uczestnicy projektu</title>
<section>
<body>

<p>
W projekcie na pełnym etacie pracują następujące osoby:
</p>

<table>
  <tr>
    <th>Imię i nazwisko</th>
    <th>Pseudonim</th>
    <th>E-mail</th>
  </tr><tr>
    <ti>Łukasz Damentko</ti><ti>rane</ti><ti><mail>rane@gentoo.org</mail></ti>
  </tr><tr>
    <ti>Damian Kuras</ti><ti>shadow</ti><ti><mail>shadoww@gentoo.org</mail></ti>
  </tr><tr>
    <ti>Waldemar Korłub</ti><ti>stawrul</ti><ti><mail>stawrul@gmail.com</mail></ti>
  </tr><tr>
    <ti>Damian Szeluga</ti><ti>Damjanek</ti><ti><mail>damjanek@gentoo.pl</mail></ti>
  </tr><tr>
    <ti>Kuba Bożanowski</ti><ti>iieee</ti><ti><mail>jbozanowski@gmail.com</mail></ti>
  </tr>
</table>

<p>
W przeszłości pomagało nam znacznie więcej osób. Poniżej znajduje się lista
nazwisk ludzi, których teksty znajdują się na polskich stronach Gentoo.
</p>

<ul>
  <li>Adrian Spaleniak</li>
  <li>Aleksander Kamil Modzelewski</li>
  <li>Antoni Grzymała</li>
  <li>Bartosz Bielecki</li>
  <li>Dawid Węgliński</li>
  <li>Hubert Kromer</li>
  <li>Janusz Bossy</li>
  <li>Jarosław Ogrodnik</li>
  <li>Jerzy Pawelec</li>
  <li>Kamil Górnik</li>
  <li>Karol Góralski</li>
  <li>Karol Wojtaszek</li>
  <li>Krzysztof Nowicki</li>
  <li>Krzysztof Smirnow</li>
  <li>Łukasz Czyżykowski</li>
  <li>Łukasz Strzygowski</li>
  <li>Marcin Kryczek</li>
  <li>Marek Więcek</li>
  <li>Mariusz Wołos</li>
  <li>Mateusz Kotyrba</li>
  <li>Michał Brudka</li>
  <li>Michał Januszewski</li>
  <li>Michał Kurgan</li>
  <li>Paweł Drobek</li>
  <li>Paweł Kilian</li>
  <li>Paweł Kwiatkowski</li>
  <li>Paweł Seremak</li>
  <li>Piotr Chmyłkowski</li>
  <li>Radosław Szkodziński</li>
  <li>Rafał Stolarski</li>
  <li>Robert Frączek</li>
  <li>Robert Muchacki</li>
  <li>Robert Sebastian Gerus</li>
  <li>Tomasz Bukowski</li>
  <li>Tomasz Jankowski</li>
  <li>Tomasz Tofel</li>
  <li>Wojciech Arabczyk</li>
  <li>Wojciech Baran</li>
  <li>Maciej Majnusz</li>
  <li>Artur Czepiel</li>
  <li>Szymon Migaj</li>
</ul>

</body>
</section>
</chapter>
</guide>

=== rane/gentoo-docs-pl/cla/gnome-config.xml
<?xml version='1.0' encoding='UTF-8'?>
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/doc/pl/gnome-config.xml,v 1.12 2007/05/24 20:24:17 rane Exp $ -->
<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">

<guide link="/doc/pl/gnome-config.xml" lang="pl">
<title>Konfigurowanie GNOME</title>

<author title="Autor">
  <mail link="swift@gentoo.org">Sven Vermeulen</mail>
</author>
<author title="Redaktor">
  <mail link="lars@strojny.net">Lars Strojny</mail>
</author>
<author title="Tłumaczenie">
  <mail link="rane@gentoo.org">Łukasz Damentko</mail>
</author>
<author title="Tłumaczenie">
  <mail link="stawrul@gmail.com">Waldemar Korłub</mail>
</author>

<abstract>
Opis wszystkich aspektów GNOME, włączając w to opis instalacji, konfiguracji i
pracy z tym środowiskiem graficznym.
</abstract>

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/2.5 -->
<license/>

<version>1.16</version>
<date>2007-07-05</date>

<chapter>
<title>Czym jest GNOME?</title>
<section>
<title>Projekt</title>
<body>

<p>
Projekt <uri link="http://www.gnome.org">GNOME</uri> to grupa osób zajmujących
się rozwijaniem środowiska graficznego o tej samej nazwie. <uri
link="http://foundation.gnome.org">Fundacja GNOME</uri> koordynuje prace i
zajmuje się niezwiązanymi z programowaniem aspektami rozwoju środowiska GNOME.
</p>

</body>
</section>
<section>
<title>Oprogramowanie</title>
<body>

<p>
GNOME to środowisko graficzne oraz platforma deweloperska i jest doskonały
wybór zarówno dla użytkowników domowych jak i dla developerów.
</p>

</body>
</section>
<section>
<title>Społeczność</title>
<body>

<p>
Tak jak każdy duży projekt otwartego oprogramowania, GNOME posiada szeroką grupę
użytkowników oraz developerów. Na stronie <uri
link="http://www.gnomedesktop.org">Footnotes</uri> znajdują się wiadomości dla
zwykłych użytkowników. Osoby bardziej zaawansowane na pewno zainteresuje za to
strona <uri link="http://planet.gnome.org">GnomePlanet</uri>, a
zainteresowanych pomocą w rozwoju środowiska GNOME strona <uri
link="http://developer.gnome.org">Developer.Gnome.Org</uri>.
</p>

</body>
</section>
</chapter>
<chapter>
<title>Instalowanie GNOME</title>
<section>
<title>Co jest potrzebne?</title>
<body>

<p>
Przed rozpoczęciem instalacji GNOME należy odpowiednio zmienić flagi USE w pliku
<path>/etc/make.conf</path> tak, aby były włączone <c>gtk</c> i <c>gnome</c>.
Jeśli potrzebna jest obsługa <c>hald</c>, warstwy abstrakcji sprzętowej, należy
dodać do listy flagę <c>hal</c>. Zmienna <c>avahi</c> doda GNOME obsługę
wykrywania DNS (podobną do Rendevouz z Mac OS X). Jeśli nie jest potrzebna
obsługa KDE (innego dużego środowiska graficznego), można usunąć z listy flagi
<c>qt</c>, <c>arts</c> i <c>kde</c>.
</p>

<pre caption="Przykładowa lista flag USE w /etc/make.conf">
USE="-qt3 -qt4 -arts -kde gtk gnome hal avahi"
</pre>

<p>
Korzystając z flagi USE <c>branding</c> uzyskamy ładny splashscreen z logo
Gentoo zamiast standardowego Gnome:
</p>

<pre caption="Dodanie elementów graficznych z marką Gentoo">
# <i>echo "gnome-base/gnome-session branding" &gt;&gt; /etc/portage/package.use</i>
</pre>

<p>
Potem można wgrać GNOME poprzez zainstalowanie pakietów <c>gnome</c>:
</p>

<pre caption="Instalowanie GNOME">
# <i>emerge gnome</i>
</pre>

<p>
Minimalne środowisko Gnome można znaleźć w pakiecie <c>gnome-light</c>:
</p>

<pre caption="Instalowanie minimalnego środowiska GNOME">
# <i>emerge gnome-light</i>
</pre>

<p>
Zajmie to chwilę. Po zakończeniu instalacji należy uaktualnić zmienne
środowiskowe:
</p>

<pre caption="Uaktualnianie zmiennych środowiskowych">
# <i>env-update &amp;&amp; source /etc/profile</i>
</pre>

<p>
Wynik polecenia <c>emerge</c> chwilę wcześniej zawierał sugestię dotyczącą
dodania <c>gamin</c> na domyślny poziom uruchomieniowy w celu umożliwienia
nautilusowi i gnome-vfs monitorowania zmian w plikach:
</p>

<pre caption="Instalowanie gamin, programu monitorującego zmiany w plikach">
# <i>emerge gamin</i>
</pre>

<impo>
Jeśli jest to zmiana z <c>fam</c> (programu, który był używany w tym samym celu
w przeszłości, należy najpierw usunąć <c>famd</c> ze wszystkich poziomów
uruchomieniowych, a następnie całkowicie odinstalować:
</impo>

<pre caption="Opcjonalnie: zamiana programu fam na gamin">
# <i>rc-update del famd</i>
# <i>emerge --unmerge app-admin/fam</i>
</pre>

<p>
Następnie należy wyczyścić wszystkie pozostałe usługi.
</p>

<pre caption="Dodawanie hald i avahi-dnsconfd na domyślny poziom uruchomienowy">
# <i>/etc/init.d/hald start</i>
# <i>rc-update add hald default</i>

# <i>/etc/init.d/avahi-dnsconfd start</i>
# <i>rc-update add avahi-dnsconfd default</i>
</pre>

</body>
</section>
<section>
<title>Pierwsze wrażenia</title>
<body>

<p>
Po pierwsze warto dowiedzieć się co właściwie się zbudowało. Opuszczamy konto
roota i logujemy się jako zwykły użytkownik. Skonfigurujemy system tak, aby
uruchamiał GNOME po każdym wpisaniu polecenia <c>startx</c>. Więcej szczegółów
na ten temat znajduje się w akapicie dotyczącym <uri
link="/doc/pl/xorg-config.xml#using_startx">używania startx</uri> w dokumencie
opisującym <uri link="/doc/pl/xorg-config.xml">konfigurację serwera X</uri>.
</p>

<pre caption="Konfigurowanie GNOME jako domyślnego środowiska">
$ <i>echo "exec gnome-session" &gt; ~/.xinitrc</i>
</pre>

<p>
Następnie uruchamiamy środowisko za pomocą polecenia <c>startx</c>:
</p>

<pre caption="Uruchamianie GNOME">
$ <i>startx</i>
</pre>

<p>
Jeśli wszystko pójdzie dobrze uruchomi się środowisko graficzne z logo GNOME.
Pora przyjrzeć się możliwym do przeprowadzenia na samym początku dodatkowym
zmianom w konfiguracji.
</p>

</body>
</section>
</chapter>
<chapter>
<title>Konfigurowanie GNOME</title>
<section>
<title>Graficzny menedżer logowania GNOME</title>
<body>

<p>
Jeśli menedżer logowania GNOME (GDM) ma być uruchamiany automatycznie po starcie
systemu tak, aby możliwe było zalogowanie się ze środowiska graficznego, należy
dodać skrypt startowy <c>xdm</c> na domyślny poziom uruchomieniowy:
</p>

<pre caption="Dodawanie xdm na domyślny poziom uruchomieniowy">
# <i>rc-update add xdm default</i>
</pre>

<p>
Następnie należy otworzyć plik <path>/etc/conf.d/xdm</path> i odpowiednio
zmienić zawartość zmiennej DISPLAYMANAGER.
</p>

<pre caption="Edytowanie /etc/conf.d/xdm">
DISPLAYMANAGER="gdm"
</pre>

<p>
Po ponownym uruchomieniu komputera pojawi się GDM i umożliwi zalogowanie się do
środowiska GNOME. Istnieje opcja uruchamiania z tego menedżera innych środowisk,
należy w tym celu wyedytować plik <path>/usr/share/xsessions/</path>. Warto
wspomnieć, że jeśli korzysta się z GDM to niepotrzebny staje się plik
<path>~/.xinitrc</path>.
</p>

<p>
W celu uruchomienia <c>hald</c> należy uruchomić <c>gnome-volume-manager</c> i
dokonać edycji ustawień. Ponadto należy dodać użytkowników do grupy
<c>plugdev</c>
</p>

</body>
</section>
</chapter>
</guide>

=== rane/gentoo-docs-pl/pressenter/manually-fixing-portage.xml
<?xml version='1.0' encoding="UTF-8"?>
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/proj/pl/portage/doc/manually-fixing-portage.xml,v 1.2 2007/05/10 14:20:13 rane Exp $ -->
<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">

<guide link="/proj/pl/portage/doc/manually-fixing-portage.xml" lang="pl">

<title>Ręczna naprawa zepsutego portage</title>

<author title="Autor">
  <mail link="genone@gentoo.org">Marius Mauch</mail>
</author>
<author title="Tłumaczenie">
  <mail link="rane@gentoo.org">Łukasz Damentko</mail>
</author>

<abstract>
Dokument ten służy pomocą ludziom, którzy muszą ręcznie naprawić zepsutą
instalację sys-apps/portage.
</abstract>

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/2.5 -->
<license/>

<version>0.3</version>
<date>2007-05-31</date>

<chapter>
<title>Ręczna naprawa portage</title>
<section>
<title>Wprowadzenie</title>
<body>

<p>
Ten tekst wyjaśnia jak należy postępować, aby naprawić lub zaktualizować zepsutą
instalację portage w przypadku gdy niemożliwe jest uruchomienie komendy
<c>emerge sys-apps/portage</c>. Nie jest to trudny proces, ale wymaga dużo
uwagi, dlatego radzimy dokładnie zapoznać się ze wszystkimi etapami naprawy.
</p>

</body>
</section>
<section>
<title>Ściąganie paczki z portage</title>
<body>

<p>
Po pierwsze musimy pobrać na dysk spakowane źródła aktualnej wersji Portage. W
przykładach posłużymy się wersją <e>portage-2.1.1</e> (ponieważ jest ona
stabilna w momencie pisania tego tekstu). Należy oczywiście zastąpić ją w
poleceniach tą której się używa.
</p>

<p>
Czasem możliwe jest wykorzystanie portage do pobrania źródeł. Należy spróbować
czy zadziała polecenie <c>emerge --fetchonly sys-apps/portage</c>. Jeśli nie
działa, trzeba pobrać źródła ręcznie.
</p>

<pre caption="Pobieranie źródeł programem wget">
# <i>wget -P /usr/portage/distfiles http://distfiles.gentoo.org/distfiles/portage-2.1.1.tar.bz2</i>
</pre>

<p>
Po wykonaniu tego polecenia paczka ze źródłami zostanie zapisana jako
<path>/usr/portage/distfiles/portage-2.1.1.tar.bz2</path>.
</p>

</body>
</section>
<section>
<title>Zastępowanie zainstalowanej wersji</title>
<body>

<p>
Następny krok to rozpakowanie paczki do tymczasowego katalogu, w przykładach tym
katalogiem będzie <path>/root/portage-recover</path>.
</p>

<pre caption="Rozpakowywanie paczki">
# <i>cd /root</i>
# <i>mkdir portage-recover</i>
# <i>cd portage-recover</i>
# <i>tar xfj /usr/portage/distfiles/portage-2.1.1.tar.bz2</i>
</pre>

<p>
Następnie należy zastąpić pliki basha i pythona z zepsutej zainstalowanej w
systemie wersji tymi z paczki. W tym celu należy wpisać:
</p>

<pre caption="Zastępowanie plików">
# <i>cd /root/portage-recover/portage-2.1.1</i>
# <i>cp -R pym bin /usr/lib/portage/</i>
</pre>

<note>
Jeżeli przypadkowo odinstalowaliśmy wcześniej portage lub zgubiliśmy
<path>/etc/make.globals</path> z innego powodu, należy w takim wypadku
skopiować również <path>cnf/make.globals</path> z powrotem do <path>/etc</path>,
jeżeli nie zostanie to wykonane nasze portage może dziwnie się zachowywać.
</note>

<p>
Po wykonaniu tego polecenia portage powinno znów działać. Ostatnią czynnością
jest wykonanie <c>emerge sys-apps/portage</c>.
</p>

<p>
Jeśli pojawi się błąd <e>command not found</e> po uruchomieniu <c>emerge</c>
należy poprawić dowiązanie symboliczne:
</p>

<pre caption="Poprawiania dowiązania do emerge">
# <i>ln -s ../lib/portage/bin/emerge /usr/bin/emerge</i>
</pre>

<p>
Jeśli powyższy proces nie rozwiązał problemu to najprawdopodobniej to nie
portage jest zepsute tylko coś innego. Niestety nie należy to już do tematyki
tego dokumentu. W takim wypadku radzimy zapoznać się z <uri
link="/proj/pl/portage/doc/common-problems.xml">listą najczęstszych
problemów</uri> lub poszukać pomocy na <uri
link="http://bugs.gentoo.org">Bugzilli</uri>.
</p>

</body>
</section>
</chapter>
</guide>

=== rane/gentoo-docs-pl/rane/test.xml
<?xml version='1.0' encoding="UTF-8"?>
<!-- $Id: test.xml,v 1.6 2007/05/14 20:49:32 rane Exp $ -->
<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">

<guide link="/doc/en/test.xml">
<title>Testfile</title>

<author title="Author">
  <mail link="pylon@gentoo.org">Lars Weiler</mail>
</author>

<abstract>
This is a testfile with some guidexml content. The main purpose is to test our
DTD checker on the CVS server.         a a
</abstract>

<license />

<version>1.74</version>
<date>2007-03-08</date>

<chapter>
<title>Sample Chapter 1</title>
<section>
<title>Sample Section 1</title>
<body>

<p>
Some text.
Some more text.
</p>

</body>
</section>
<section>
<title>Sample Section 2</title>
<body>

<p>
<b>Some bold text</b> and <e>emphasised</e>.
</p>

<p>
Testing gentoo-doc-cvs mailing list.
</p>

</body>
</section>
</chapter>

</guide>
