=== rane/gentoo-docs-pl/rane/www/guide.dtd
<!ENTITY doctable SYSTEM "doctable.xml">
<!ENTITY peopletable SYSTEM "peopletable.xml">
<!ENTITY dictionary SYSTEM "dictionary.xml">
<!ENTITY  % style.class	"b|box|brite|c|codenote|comment|e|i|path">
<!ENTITY  % link.class	"uri|mail">
<!ENTITY  % logic.class	"figure|fig|img|br|note|impo|warn|pre|p|table|ul|ol">
<!ENTITY  % all.class	"%logic.class;|%style.class;|%link.class;">

<!ENTITY half   "&#x00BD;"> <!-- VULGAR FRACTION ONE HALF -->
<!ENTITY frac12 "&#x00BD;"> <!-- VULGAR FRACTION ONE HALF -->
<!ENTITY frac14 "&#x00BC;"> <!-- VULGAR FRACTION ONE QUARTER -->
<!ENTITY frac34 "&#x00BE;"> <!-- VULGAR FRACTION THREE QUARTERS -->
<!ENTITY frac18 "&#x215B;"> <!--  -->
<!ENTITY frac38 "&#x215C;"> <!--  -->
<!ENTITY frac58 "&#x215D;"> <!--  -->
<!ENTITY frac78 "&#x215E;"> <!--  -->
<!ENTITY sup1   "&#x00B9;"> <!-- SUPERSCRIPT ONE -->
<!ENTITY sup2   "&#x00B2;"> <!-- SUPERSCRIPT TWO -->
<!ENTITY sup3   "&#x00B3;"> <!-- SUPERSCRIPT THREE -->
<!ENTITY plus   "&#x002B;"> <!-- PLUS SIGN -->
<!ENTITY plusmn "&#x00B1;"> <!-- PLUS-MINUS SIGN -->
<!ENTITY lt     "&#38;#60;"> <!-- LESS-THAN SIGN -->
<!ENTITY equals "&#x003D;"> <!-- EQUALS SIGN -->
<!ENTITY gt     "&#x003E;"> <!-- GREATER-THAN SIGN -->
<!ENTITY divide "&#x00F7;"> <!-- DIVISION SIGN -->
<!ENTITY times  "&#x00D7;"> <!-- MULTIPLICATION SIGN -->
<!ENTITY curren "&#x00A4;"> <!-- CURRENCY SIGN -->
<!ENTITY pound  "&#x00A3;"> <!-- POUND SIGN -->
<!ENTITY dollar "&#x0024;"> <!-- DOLLAR SIGN -->
<!ENTITY cent   "&#x00A2;"> <!-- CENT SIGN -->
<!ENTITY yen    "&#x00A5;"> <!-- YEN SIGN -->
<!ENTITY num    "&#x0023;"> <!-- NUMBER SIGN -->
<!ENTITY percnt "&#x0025;"> <!-- PERCENT SIGN -->
<!ENTITY amp    "&#38;#38;"> <!-- AMPERSAND -->
<!ENTITY ast    "&#x2217;"> <!-- ASTERISK OPERATOR -->
<!ENTITY commat "&#x0040;"> <!-- COMMERCIAL AT -->
<!ENTITY lsqb   "&#x005B;"> <!-- LEFT SQUARE BRACKET -->
<!ENTITY bsol   "&#x005C;"> <!-- REVERSE SOLIDUS -->
<!ENTITY rsqb   "&#x005D;"> <!-- RIGHT SQUARE BRACKET -->
<!ENTITY lcub   "&#x007B;"> <!-- LEFT CURLY BRACKET -->
<!ENTITY horbar "&#x2015;"> <!-- HORIZONTAL BAR -->
<!ENTITY verbar "&#x007C;"> <!-- VERTICAL LINE -->
<!ENTITY rcub   "&#x007D;"> <!-- RIGHT CURLY BRACKET -->
<!ENTITY micro  "&#x00B5;"> <!-- MICRO SIGN -->
<!ENTITY ohm    "&#x2126;"> <!-- OHM SIGN -->
<!ENTITY deg    "&#x00B0;"> <!-- DEGREE SIGN -->
<!ENTITY ordm   "&#x00BA;"> <!-- MASCULINE ORDINAL INDICATOR -->
<!ENTITY ordf   "&#x00AA;"> <!-- FEMININE ORDINAL INDICATOR -->
<!ENTITY sect   "&#x00A7;"> <!-- SECTION SIGN -->
<!ENTITY para   "&#x00B6;"> <!-- PILCROW SIGN -->
<!ENTITY middot "&#x00B7;"> <!-- MIDDLE DOT -->
<!ENTITY larr   "&#x2190;"> <!-- LEFTWARDS DOUBLE ARROW -->
<!ENTITY rarr   "&#x2192;"> <!-- RIGHTWARDS DOUBLE ARROW -->
<!ENTITY uarr   "&#x2191;"> <!-- UPWARDS ARROW -->
<!ENTITY darr   "&#x2193;"> <!-- DOWNWARDS ARROW -->
<!ENTITY copy   "&#x00A9;"> <!-- COPYRIGHT SIGN -->
<!ENTITY reg    "&#x00AE;"> <!-- REG TRADE MARK SIGN -->
<!ENTITY trade  "&#x2122;"> <!-- TRADE MARK SIGN -->
<!ENTITY brvbar "&#x00A6;"> <!-- BROKEN BAR -->
<!ENTITY not    "&#x00AC;"> <!-- NOT SIGN -->
<!ENTITY sung   "&#x2669;"> <!--  -->
<!ENTITY excl   "&#x0021;"> <!-- EXCLAMATION MARK -->
<!ENTITY iexcl  "&#x00A1;"> <!-- INVERTED EXCLAMATION MARK -->
<!ENTITY quot   "&#x0022;"> <!-- QUOTATION MARK -->
<!ENTITY apos   "&#x0027;"> <!-- APOSTROPHE -->
<!ENTITY lpar   "&#x0028;"> <!-- LEFT PARENTHESIS -->
<!ENTITY rpar   "&#x0029;"> <!-- RIGHT PARENTHESIS -->
<!ENTITY comma  "&#x002C;"> <!-- COMMA -->
<!ENTITY lowbar "&#x005F;"> <!-- LOW LINE -->
<!ENTITY hyphen "&#xE4F8;"> <!--  -->
<!ENTITY period "&#x002E;"> <!-- FULL STOP -->
<!ENTITY sol    "&#x002F;"> <!-- SOLIDUS -->
<!ENTITY colon  "&#x003A;"> <!-- COLON -->
<!ENTITY semi   "&#x003B;"> <!-- SEMICOLON -->
<!ENTITY quest  "&#x003F;"> <!-- QUESTION MARK -->
<!ENTITY iquest "&#x00BF;"> <!-- INVERTED QUESTION MARK -->
<!ENTITY laquo  "&#x00AB;"> <!-- LEFT-POINTING DOUBLE ANGLE QUOTATION MARK -->
<!ENTITY raquo  "&#x00BB;"> <!-- RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK -->
<!ENTITY lsquo  "&#x2018;"> <!--  -->
<!ENTITY rsquo  "&#x2019;"> <!-- RIGHT SINGLE QUOTATION MARK -->
<!ENTITY ldquo  "&#x201C;"> <!--  -->
<!ENTITY rdquo  "&#x201D;"> <!-- RIGHT DOUBLE QUOTATION MARK -->
<!ENTITY nbsp   "&#x00A0;"> <!-- NO-BREAK SPACE -->
<!ENTITY shy    "&#x00AD;"> <!-- SOFT HYPHEN -->

<!ELEMENT guide			(title, subtitle?, author+, abstract, license?, version, date, newsitems?, chapter+)>
<!ATTLIST guide			type (project) #IMPLIED
						link CDATA #IMPLIED
						mainpage (yes|no) "no"
						mainid (news|about|contract|packages|graphics|articles|docs|changelog|projects) #IMPLIED>
<!ELEMENT newsitems		(news+)>
<!ELEMENT news			(poster, date, title, body)>
<!ATTLIST news			gentoo (yes|no) "no"
						category (gentoo|main|ibm|linux|moo|nvidia) #REQUIRED>
<!ELEMENT title			(#PCDATA|%style.class;)*>
<!ELEMENT subtitle		(#PCDATA)>
<!ELEMENT author		(#PCDATA|mail)*>
<!ATTLIST author		title CDATA #IMPLIED>
<!ELEMENT abstract		(#PCDATA)>
<!ELEMENT license		EMPTY>
<!ELEMENT version		(#PCDATA)>
<!ELEMENT date			(#PCDATA)>
<!ELEMENT chapter		(title, section+)>
<!ATTLIST chapter   id CDATA #IMPLIED>
<!ELEMENT section		(title?, body)>
<!ATTLIST section   id CDATA #IMPLIED>
<!ELEMENT body			(%all.class;)*>
<!ELEMENT figure		EMPTY>
<!ATTLIST figure		caption CDATA #IMPLIED
						short CDATA #IMPLIED
						link CDATA #REQUIRED>
<!ELEMENT fig			EMPTY>
<!ATTLIST fig			short CDATA #IMPLIED
						linkto CDATA #IMPLIED
						link CDATA #REQUIRED>
<!ELEMENT img			EMPTY>
<!ATTLIST img			src CDATA #REQUIRED>
<!ELEMENT br			(#PCDATA)>
<!ELEMENT note			(#PCDATA|%all.class;)*>
<!ELEMENT impo			(#PCDATA|%all.class;)*>
<!ELEMENT warn			(#PCDATA|%all.class;)*>
<!ELEMENT pre			(#PCDATA|%all.class;)*>
<!ATTLIST pre			caption CDATA #IMPLIED>
<!ELEMENT p				(#PCDATA|%all.class;)*>
<!ELEMENT table			(tcolumn*, tr+)>
<!ELEMENT tcolumn		EMPTY>
<!ATTLIST tcolumn		width CDATA #REQUIRED>
<!ELEMENT tr			(th+|ti+)>
<!ELEMENT th			(#PCDATA|%all.class;)*>
<!ELEMENT ti			(#PCDATA|%all.class;)*>
<!ELEMENT ul			(li+)>
<!ELEMENT ol			(li+)>
<!ELEMENT li			(#PCDATA|%all.class;)*>

<!--STYLE TAGS-->
<!ELEMENT b				(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT brite			(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT box			(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT c				(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT codenote		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT comment		(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT e				(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT i				(#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT path			(#PCDATA|%style.class;|%link.class;)*>

<!--LINK TAGS-->
<!ELEMENT mail			(#PCDATA|%style.class;)*>
<!ATTLIST mail			link CDATA #REQUIRED>
<!ELEMENT uri			(#PCDATA|%style.class;)*>
<!ATTLIST uri			link CDATA #IMPLIED>

=== rane/gentoo-docs-pl/cla/apache-upgrading.xml
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/doc/pl/apache-upgrading.xml,v 1.7 2007/03/24 11:21:36 nightmorph Exp $ -->

<guide link="/doc/pl/apache-upgrading.xml" lang="pl">

<title>Aktualizacja serwera Apache</title>

<author title="Autor">
  <mail link="vericgar@gentoo.org">Michael Stewart</mail>
</author>
<author title="Tłumacz">
  <mail link="lucass@gentoo.org">Łukasz Strzygowski</mail>
</author>

<abstract>
Dokument opisuje proces bezpiecznej aktualizacji Apache.
</abstract>

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/2.5 -->
<license/>

<version>2.5</version>
<date>2007-07-30</date>

<chapter>
<title>Wstęp</title>
<section>
<body>

<p>
Stan pakietów z Apache i jego modułami zaczął się pogarszać. Liczne problemy
utrudniały pracę grupy opiekującej się Apache oraz pomoc użytkownikom:
</p>

<ul>
  <li>
    Konfiguracja dostarczana z Gentoo znacznie różniła się od domyślnej, jakiej
    oczekiwała większość użytkowników
  </li>
  <li>
    Wiele modułów używało podobnego kodu, ale robiło wszystko na swój sposób
  </li>
  <li>
    Większość modułów nie była dobrze zarządzana - przede wszystkim z powodu ich
    dużej ilości
  </li>
  <li>Moduły nie posiadały standardowej konfiguracji</li>
  <li>
    Niektóre moduły współpracowały z obiema wersjami Apache, ale ebuildy tego
    nie obsługiwały
  </li>
  <li>
    Niektóre funkcje Apache nie były dostępne dla użytkowników Gentoo (na
    przykład MPM)
  </li>
  <li>Błędy związane z Apache nawarstwiały się</li>
</ul>

<p>
Jak to rozwiązano? Do grupy Apache dołączyło kilku nowych członków, którzy
wspólnie stworzyli nową eclassę, zaktualizowali wszystkie moduły oraz rozwiązali
wiele bugów.
</p>

<p>
Dokument ten szczegółowo opisuje bezpieczny dla systemu proces aktualizacji
apache. Deweloperzy oraz zainteresowani zmianami użytkownicy, którzy chcieliby
sie dowiedzieć jak zmodyfikować ebuildy, żeby korzystały z nowej eclassy mogą
znaleźć więcej informacji w <uri link="/doc/en/apache-developer.xml">Apache
Developer Reference</uri>.
</p>

</body>
</section>
</chapter>

<chapter id="upgrade">
<title>Opis aktualizacji</title>
<section>
<body>

<p>
Wprowadziliśmy wiele zmian w działaniu Apache pod Gentoo. Każdy pakiet,
który jest z nim bezpośrednio związany, musi zostać zaktualizowany.
Nie wszystko będzie działać tak jak wcześniej.
</p>

<p>
Po pierwsze, musimy dowiedzieć się, które pakiety należy zaktualizować.
Możemy skorzystać w tym celu z programu <c>equery</c>, należącego do
pakietu <c>app-portage/gentoolkit</c>.
</p>


<pre caption="Wyszukiwanie pakietów do aktualizacji">
$ <i>equery depends www-servers/apache</i>
[ Searching for packages depending on www-servers/apache... ]
dev-db/phpmyadmin-2.5.6
dev-php/mod_php-4.3.10
dev-php/phpsysinfo-2.1-r2
net-www/mod_bandwidth-2.0.5
net-www/mod_layout-4.0.1a
net-www/mod_mp3-0.40
net-www/mod_random-2.0
net-www/mod_throttle-3.1.2-r1
net-www/mod_ldap_userdir-1.1.4
www-apache/mod_loopback-1.04
www-apache/mod_watch-3.18
www-apps/viewcvs-0.9.2_p20030430
</pre>

<impo>
Lista pakietów, które mamy zainstalowane w systemie, może się znacznie różnić od
powyższej. Musimy wykonać podane polecenie samodzielnie.
</impo>

<warn>
W Portage wciąż są moduły i pakiety zależne od Apache, które nie zostały jeszcze
zaktualizowane. Warto poszukać bugów dotyczących wszystkich krytycznych pakietów
związanych z Apache jakich używamy w <uri
link="http://bugs.gentoo.org">Bugzilli</uri>.
</warn>


<p>
Wprowadzone zmiany nie dotyczą wielu aplikacji internetowych, w większości
korzystających z eclassy <c>webapp</c>, która kontroluje ich poprawną
instalację. Można sprawdzić czy zostały zaktualizowane w nowej wersji pakietu.
</p>

<p>
Ponieważ dodaliśmy kilka nowych flag USE, warto je przejrzeć i dodać odpowiednie
wpisy do <path>/etc/portage/package.use</path>.  Więcej informacji znajduje się
w rozdziale <uri link="#use">Flagi USE dotyczące Apache</uri>.
</p>


<pre caption="Aktualizacja pakietów z nowymi flagami USE">
<comment>(Aby wyświetlić nowe flagi USE i niezbędne aktualizacje)</comment>
# <i>emerge --pretend --verbose --update --newuse --deep apache subversion \
mod_php mod_bandwidth mod_layout mod_ldap_userdir mod_loopback mod_mp3 \
mod_random mod_throttle mod_watch</i>

<comment>(Aby zaktualizować pakiety)</comment>
# <i>emerge --verbose --update --newuse --deep apache subversion mod_php \
mod_bandwidth mod_layout mod_ldap_userdir mod_loopback mod_mp3 mod_random \
mod_throttle mod_watch</i>

<comment>(Aktualizacja samego world może okazać się łatwiejsza)</comment>
# <i>emerge --ask --verbose --update --newuse --deep world</i>
</pre>

<p>
Teraz musimy ponownie skonfigurować Apache oraz jego moduły. Zaczniemy od
aktualizacji plików w <path>/etc/init.d</path> oraz <path>/etc/conf.d</path> za
pomocą narzędzi <c>etc-update</c> lub <c>dispatch-conf</c>.  Nie wyświetlą one
plików konfiguracyjnych apache, ponieważ wszystkie zostały przeniesione do
innych lokalizacji.
</p>

<p>
Jeśli wprowadziliśmy zmiany do domyślnych plików <path>apache.conf</path> oraz
<path>commonapache.conf</path>, będziemy musieli je przepisać w
<path>/etc/apache{|2}/httpd.conf</path>. Zmieniły się ścieżki do plików
konfiguracyjnych modułów oraz vhostów. Obecnie znajdują się odpowiednio w
katalogach <path>/etc/apache2/modules.d</path> oraz
<path>/etc/apache2/vhosts.d</path>.
</p>

<p>
Kiedy skończymy przepisywać nasze zmiany do nowych plików konfiguracyjnych,
musimy usunąć poprzednie (lub gdzieś je przenieść). Poprawiony
<path>/etc/init.d/apache{|2}</path> nie pozwala uruchomić apache jeśli wciąż
istnieją, zakładając, że ponownie skonfigurowaliśmy apache korzystając z nowych
plików.
</p>

<note>
Wiele modułów, które wcześniej były aktywowane domyślnie, teraz jest
wyłączonych. Jeśli potrzebujemy tych wbudowanych w apache, wystarczy
odkomentować odpowiednie linie w httpd.conf. Jeśli chcemy skorzystać z modułów
zewnętrznych, musimy odszukać w ich konfiguracji <c>IfDefine</c> i dodać ich
nazwy do <path>/etc/conf.d/apache{|2}</path>.
</note>

<p>
Następnie ponownie uruchamiamy apache.
</p>

<pre caption="Ponowne uruchamianie apache">
# <i>/etc/init.d/apache stop</i>
# <i>/etc/init.d/apache start</i>
</pre>


<p>
Jeśli natrafimy na jakieś problemy, powinniśmy przeczytać <uri
link="/doc/pl/apache-troubleshooting.xml">Apache Troubleshooting Guide</uri>.
Jeżeli nie znajdziemy tam rozwiązania, należy je zgłosić w  <uri
link="http://bugs.gentoo.org">bugzilli</uri>. W raporcie błędu trzeba wymienić
używane moduły oraz (jeżeli korzystamy z Apache 2) flagi USE dotyczące MPM z
jakich korzystamy. Pomoc można uzyskać także na kanale
<path>#gentoo-apache</path> w sieci <path>irc.freenode.net</path>.
</p>

</body>
</section>
</chapter>

<chapter id="use">
<title>Flagi USE dotyczące Apache</title>
<section>
<body>

<p>
Apache i jego moduły korzystają z pewnych specyficznych flag USE. Oczywiście
obsługują także bardziej standardowe flagi, jednak nie opisujemy ich zachowania,
ponieważ nie różni się znacznie od tego w innych pakietach. Wszystkie
obsługiwane flagi można wyświetlić poleceniem <c>emerge --verbose --pretend
apache</c>.
</p>

<table>
<tr>
  <th>Flaga USE</th>
  <th>Pakiety</th>
  <th>Opis</th>
</tr>
<tr>
  <ti>apache2</ti>
  <ti>eclassa depend.apache (wszystkie moduły)</ti>
  <ti>
    Powinna być włączona jeśli chcemy korzystać z Apache 2.0 lub wyłączona
    jeżeli wolimy Apache 1.3. Eclassa używa jej do ustalenia wersji jaką dodać
    do zależności.</ti>
</tr>
<tr>
  <ti>mpm-leader</ti>
  <ti>apache-2*</ti>
  <ti>
    Buduje MPM <uri
    link="http://httpd.apache.org/docs/2.0/mod/leader.html">leader</uri>
  </ti>
</tr>
<tr>
  <ti>mpm-metux</ti>
  <ti>apache-2*</ti>
  <ti>Buduje MPM <uri link="http://www.metux.de/mpm/">metux</uri></ti>
</tr>
<tr>
  <ti>mpm-peruser</ti>
  <ti>apache-2*</ti>
  <ti>
    Buduje MPM <uri link="http://www.telana.com/peruser.php">peruser</uri>
  </ti>
</tr>
<tr>
  <ti>mpm-prefork</ti>
  <ti>apache-2*</ti>
  <ti>
    Buduje MPM <uri
    link="http://httpd.apache.org/docs/2.0/mod/prefork.html">prefork</uri></ti>
</tr>
<tr>
  <ti>mpm-threadpool</ti>
  <ti>apache-2*</ti>
  <ti>
    Buduje MPM <uri
    link="http://httpd.apache.org/docs/2.0/mod/threadpool.html">threadpool</uri>
  </ti>
</tr>
<tr>
  <ti>mpm-worker</ti>
  <ti>apache-2*</ti>
  <ti>
    Buduje MPM <uri
    link="http://httpd.apache.org/docs/2.0/mod/worker.html">worker</uri></ti>
</tr>
<tr>
  <ti>no-suexec</ti>
  <ti>apache</ti>
  <ti>
    Wyłącza budowanie modułu suexec (dla tych, którzy nie chcą potencjalnie
    niebezpiecznej binarki z bitem suid)
  </ti>
</tr>
<tr>
  <ti>static-modules</ti>
  <ti>apache</ti>
  <ti>
    Włącza statyczne linkowanie modułów z apache, przez co korzystanie z
    LoadModule do ładowania podstawowych modułów nie jest konieczne.
  </ti>
</tr>
<tr>
  <ti>lingerd</ti>
  <ti>apache-1*</ti>
  <ti>
    Włącza obsługę <uri
    link="http://www.iagora.com/about/software/lingerd/">lingerd</uri>
  </ti>
</tr>
<tr>
  <ti>no-htdocs</ti>
  <ti>gentoo-webroot-default</ti>
  <ti>
    Wyłącza instalowanie domyślnego webroot do <path>/var/www/localhost</path>,
    przez co zmodyfikowane pliki nie są nadpisywane. Zamiast tego, webroot jest
    instalowany w <path>/usr/share/doc/gentoo-webroot-default-*/webroot/</path>.
  </ti>
</tr>
</table>

<note>
Flagi USE mpm-* wzajemnie się wykluczają. Powinniśmy włączyć tylko jedną z nich.
(Jeśli nie aktywujemy żadnej, użyta zostanie mpm-prefork lub mpm-worker, w
zależności od tego czy włączona jest flaga threads).
</note>

</body>
</section>
</chapter>

</guide>

=== rane/gentoo-docs-pl/pressenter/gnome-2.16-upgrade.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/proj/pl/desktop/gnome/howtos/gnome-2.16-upgrade.xml,v 1.2 2007/04/05 18:49:17 shadoww Exp $ -->

<guide link="/proj/pl/desktop/gnome/howtos/gnome-2.16-upgrade.xml">

<title>Aktualizacja Gnome do wersji 2.16</title>
<author title="Autor">
  <mail link="dang@gentoo.org">Daniel Gryniewicz</mail>
</author>
<author title="Tłumaczenie">
  <mail link="dawid.weglinski@gmail.com">Dawid Węgliński</mail>
</author>

<abstract>
W przewodniku tym opisano jak należy dokonać aktualizacji GNOME 2.14.x do
2.16.x.
</abstract>

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/2.5 -->
<license/>

<version>1.0</version>
<date>2006-09-08</date>

<chapter>
<title>Rozwiązywanie problemów</title>
<section>
<title>Znane błędy budowy</title>
<body>

<p>
<c>libnotify</c> buduje różnie na bazie zainstalowanej w systemie wersji GTK+.
Jeśli wystąpiły problemy podczas budowy na przykład <c>zenity</c> lub
<c>rhythmbox</c>, które nie powiodły się z niezdefiniowanym odwołaniem do
powiadomienia funkcji, należy przebudować <c>libnotify</c> po aktualizacji GTK+
do wersji 2.10.x.
</p>

</body>
</section>
<section>
<title>gnome-settings-daemon zawodzi podczas uruchamiania</title>
<body>

<p>
<c>gnome-settings-daemon</c> do działania  wymaga lokalnej sesji dbus. Jego
uruchomienie zawodzi zatem, jeśli sesja nie jest obecna. Sesja Gnome
<c>gnome-session</c> zwykle automatycznie uruchamia sesję dbus. Nie jest to
regułą, kiedy używa się innego Menadżera Okien (WM) lub też polecenia
<c>startx</c> z plikiem <path>~/.xinitrc</path>. W takim przypadku należy
ręcznie uruchomić sesję dbus, dodając następującą linijkę do pliku
uruchamiającego X (<path>~/.xinit</path> dla <c>startx</c>,
<path>~/.xsession</path> dla Menadżera Logowania):
</p>

<pre caption="Uruchamianie sesji dbus">
eval `dbus-launch --exit-with-session --sh-syntax`
</pre>

<p>
Należy się upewnić, że powyższy skrypt został dopisany powyżej linii
<c>gnome-settings-daemon</c>.
</p>

<p>
Alternatywnie, przy użyciu startx i bez specjalnych ustawień w .xinitrc, możliwe
jest usunięcie <path>~/.xinitrc</path> i ustawienie zmiennej XSESSION="gnome" w
pliku <path>~/.profile</path> lub <path>/etc/rc.conf</path>. To poprawnie
uruchomi sesję dbus zanim zostanie uruchomiona sesja gnome.
</p>

</body>
</section>
<section>
<title>Dostawca IMAP 4rev1 nie jest dostępny w Evolution</title>
<body>

<p>
Dostawca IMAP 4rev1 został usunięty z <c>evolution</c> w tej wersji, ponieważ
jest uszkodzony i niewspierany. Użytkownicy powinni zmienić swoje konta, aby
używały normalnego dostawcy IMAP.
</p>

</body>
</section>
</chapter>
</guide>

=== rane/gentoo-docs-pl/rane/jak-aktualizowac.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">

<guide link="jak-aktualizowac.xml" lang="pl">
<title>Aktualizacja tłumaczeń dokumentacji Gentoo</title>

<author title="Autor">
  <mail link="rane@gentoo.pl">Łukasz Damentko</mail>
</author>

<abstract>
Opis dla osób chcących pomóc w aktualizowaniu polskich wersji dokumentów
dostępnych na oficjalnych stronach Gentoo.
</abstract>

<version>1.0</version>
<date>2005-19-08</date>

<chapter>
<title>Wprowadzenie</title>
<section>
<body>

<p>
Postaram się tu możliwie krótko omówić proces aktualizowania polskiego
dokumentu znajdującego się w <uri
link="http://gentoo.org/doc/pl/list.xml">zasobach dokumentacji Gentoo</uri>.
</p>

<p>
Aktualizowanie przetłumaczonej dokumentacji jest ważnym aspektem pracy nad nią i
jest niezbędne, aby nadal była przydatna dla użytkowników naszej bardzo szybko
rozwijającej się dystrybucji. Zajmuje zdecydowanie mniej czasu niż tłumaczenie
dokumentów od zera, zwykle jest to kilka kosmetycznych poprawek, czasem trzeba
dopisać jakiś akapit lub usunąć nieaktualne informacje. Jest to dobry wybór dla
osób chcących nam pomóc, ale nie dysponujących zbyt dużą ilością wolnego czasu.
</p>

<p>
Przy aktualizacji skorzystamy z kilku bardzo wygodnych i intuicyjnych narzędzi,
które znacznie ułatwią naszą pracę. Przede wszystkim będzie to tabela znajdująca
się na <uri link="http://dev.gentoo.org/~rane/trads.xml">oficjalnej stronie
projektu</uri>, która umożliwi wyświetlenie różnic pomiędzy wersjami
angielskimi. Omówimy też proces tworzenia pliku diff zawierającego naszą
aktualizację oraz sposoby podzielenia się nim ze społecznością Gentoo.
</p>

<p>
Wszystkie pytania, uwagi i propozycje zmian tego tekstu należy zgłaszać do <mail
link="rane@gentoo.org">koordynatora</mail> polskiego projektu tłumaczenia
dokumentacji Gentoo.
</p>

<p>
Jeśli będzie to pierwsza praca wykonywana przy dokumentacji Gentoo, warto
przedtem zapoznać się z <uri
link="http://dev.gentoo.org/~rane/jak-tlumaczyc.xml">przewodnikiem dla tłumaczy
dokumentacji Gentoo na język polski</uri>.
</p>

</body>
</section>
</chapter>

<chapter>
<title>Aktualizowanie dokumentu</title>
<section>
<title>Wybieranie dokumentu do aktualizacji i pobieranie go na dysk</title>
<body>

<p>
Zaczynamy od udania się pod adres
<uri>http://dev.gentoo.org/~rane/trads-0.xml</uri> i przyjrzenia się
znajdującej się tam tabeli z listą dokumentów. Musimy wybrać tekst, który
będziemy aktualizować. Na samym początku musimy znaleźć nieaktualny dokument,
najłatwiej zrobić to przeglądając kolumnę zatytułowaną <e>Diff wersji
angielskich</e>. Większość pól tej kolumny powinna być pusta, wpisy znajdują
się tylko w wierszach z nieaktualnymi dokumentami. Również kolorowe kropki
powinny ułatwić namierzenie takiego tekstu. Zielona oznacza, że dokument jest
aktualny, a żółta, pomarańczowa i czerwona informują o tym, że nie został
jeszcze poprawiony.
</p>

<p>
Zatem wybieramy któryś z nieaktualnych plików (warto wybierać najpierw te z
większą ilością kropek, są bardziej nieaktualne od pozostałych). Wyższy
priorytet mają dokumenty z kropkami czerwonymi niż te z żółtymi.
</p>

<figure link="images/tabela.jpg" caption="Wycinek tabeli"/>

<p>
W celu pobrania tłumaczenia klikamy prawym klawiszem myszki we wpis <c>(xml)</c>
w kolumnie <e>Wersja polska</e> i zapisujemy plik na dysku.
</p>

</body>
</section>
<section>
<title>Znajdowanie różnic między wersjami angielskimi</title>
<body>

<p>
Sprawa jest prosta, wystarczy kliknąć w odnośnik w kolumnie zatytułowanej
<e>Diff wersji angielskich</e>, a program view-cvs wyświetli nam ładnie
pokolorowany plik, w którym zostaną wymienione wszystkie różnice między wersjami
oryginału, które trzeba będzie nanieść na polskie tłumaczenie.  
</p>

<figure link="images/diff.jpg" caption="Strona z diffem"/>

<p>
W lewej kolumnie znajduje się wersja dokumentu, która była tłumaczona, a w
prawej aktualna wersja. Linie zaznaczone na czerwono zostały usunięte z
oryginału, żółte zostały zmienione, a zielone dodane. Warto zapoznać się
pokrótce ze wszystkimi zmianami w dokumencie i poznać ich charakter przed
przejściem do następnego kroku, czyli nanoszenia poprawek na tłumaczenie.
</p>

</body>
</section>
<section>
<title>Nanoszenie poprawek na tłumaczenie</title>
<body>

<p>
Otwieramy ściągnięty przed chwilą plik z polską wersją tekstu w ulubionym
edytorze i zmieniamy w nim wszystkie wpisy, które uległy zmianie w oryginale.
Zwykle tłumaczenia są bardzo wierne i nie ma problemu z namierzeniem
odpowiednich akapitów, w których trzeba wprowadzić zmiany.
</p>

<p>
Dodajemy, usuwamy lub zmieniamy wszystkie linie tak, aby polskie tłumaczenie
znów odpowiadało wersji oryginalnej. Warto również przejrzeć jeszcze raz cały
dokument i poprawić w nim ewentualne błędy oraz sprawdzić czy dodane zdania
dobrze wkomponowały się w jego treść.
</p>

</body>
</section>
<section>
<title>Tworzenie i wysyłanie diffa</title>
<body>

<p>
Po zakończeniu prac nad aktualizacją należy utworzyć plik diff zawierający
różnice między dokumentami i wysłać go pod adres <mail>rane@gentoo.org</mail>.
</p>

<pre caption="Tworzenie diffa">
$ <i>diff -Naur stary.xml nowy.xml > plik.diff</i>
</pre>

<impo>
Żeby wszystko było jasne: <c>stary.xml</c> to plik xml, który początkowo
pobraliśmy na dysk, <c>nowy.xml</c> to plik, na który naniesiono poprawki, a
<c>plik.diff</c> to plik zawierający aktualizację, który trzeba będzie wysłać na
adres <mail>rane@gentoo.org</mail>.
</impo>

<note>
Program <c>diff</c> jest częścią pakietu sys-apps/diffutils wchodzącego w skład
kategorii "system" pakietów Gentoo. W związku z tym powinien być gotów do użycia
bez żadnych dodatkowych instalacji i zmian w plikach konfiguracyjnych.
</note>

<p>
Przypominamy także, że wszystkie niejasności jakie pojawiły się przy lekturze
tego tekstu można rozwiać zadając pytanie <mail
link="rane@gentoo.org">koordynatorowi</mail> projektu. Z uczestnikami projektu
można porozmawiać na kanale <uri
link="http://dev.gentoo.org/~rane/jak-tlumaczyc.xml#doc_chap6">#gentoo-docs-pl</uri>
w sieci freenode lub na naszej <uri
link="http://dev.gentoo.org/~rane/jak-tlumaczyc.xml#doc_chap6">liście
mailingowej</uri>.
</p>

</body>
</section>
<section>
<title>Kodowanie UTF-8</title>
<body>

<p>
Pewną trudnością może okazać się fakt, że cała dokumentacja Gentoo napisana jest
w kodowaniu UTF-8, które wciąż nie jest w naszym kraju zbyt popularne.
</p>

<p>
Można uporać się z tym na kilka sposobów, np. przestawiając edytor do pracy w
kodowaniu UTF-8. Można również wykorzystać program <c>recode</c>, który pozwala
na łatwą konwersję między kodowaniami.
</p>

<pre caption="Zmiana kodowania dokumentu za pomocą programu recode">
<comment>(Zaczniemy od zainstalowania programu)</comment>
# <i>emerge app-text/recode</i>
<comment>(Następnie przekonwertujemy plik z UTF-8 na ISO8859-2)</comment>
$ <i>recode u8..l2 plik.xml</i>
<comment>(Po zakończonej pracy i przed przygotowaniem diffa konieczne będzie ponowne przejście na UTF-8)</comment>
$ <i>recode l2..u8 plik.xml</i>
</pre>

<p>
Obsługa programu jest intuicyjna, <c>l2</c> oznacza kodowanie ISO8859-2,
<c>u8</c> kodowanie UTF-8. Jako parametr podajemy dodatkowo nazwę pliku xml,
który będziemy aktualizować.
</p>


</body>
</section>
</chapter>

</guide>
